Online-Booking-System/config/routes.rb
Rails.application.routes.draw do
  
  
  resources :activities do
 resources :applications
  end
  resources :parents do
	resources :parents
end 
		resources :users
  resources :teachers

  
resources :students
  
  root 'welcome#index'
  get '/approve' => 'welcome#approve'
  get 'admins/add'=> 'welcome#new'
  post '/approve' => 'welcome#authen'	  
  post 'admins/add' => 'welcome#add_admin'
  get '/register' => 'parents#new'
  get '/registerteacher' => 'teachers#new'
  get '/students/:id/activities' => 'students#activity'

  get '/parents/homepage' => 'sessions#homepage'
  
  delete '/logout' => 'sessions#destroy'	
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/newclass' => 'subjects#new'
  post '/newclass' => 'subjects#create'

   

end

Online-Booking-System/app/models/parent.rb
class Parent < ActiveRecord::Base
	has_one :user,as: :userable,dependent: :destroy
	has_many :students,dependent: :destroy
	accepts_nested_attributes_for :user
	accepts_nested_attributes_for :students,reject_if: proc { |attributes| attributes['first_name'].nil? },allow_destroy: true
		
	validates :user,presence: true
    validates :students,presence: true
	def self.update_students(parent)
		parent.update params[:parent] 
	end
end

Online-Booking-System/app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action  only: [:show, :edit, :update, :destroy]
  include SessionsHelper
  # GET /parents
  # GET /parents.json
  def index
	redirect_to login_url unless !current_user.nil? and current_user.authenticated?  and current_user.admin?
    @parents = Parent.all if !current_user.nil? and current_user.admin? and current_user.authenticated?
  end
 
  def show
	path = request.original_url.split('/')[-1]
	@cur_parent =Parent.find_by(id: path.to_i)
	redirect_to login_url unless !current_user.nil? and current_user.authenticated? and (@cur_parent.id == current_user.id or current_user.admin?) 
  end

  # GET /parents/new
  def new
	@parent.students.delete unless @parent.nil? or @parents.students.nil?
		@parent = Parent.new
	params[:students] = nil
	if logged_in?
		flash[:message] = "Already logged in"
		redirect_to root_url
	else
   	@parent.build_user
	@parent.students << Student.new

	end
  end

  # GET /parents/1/edit
  def edit
	@parent = nil	
	path = request.original_url.split('/')[-2]
	@parent =Parent.find_by(id: path.to_i)
	@user = User.find_by(userable_id: @parent.id,userable_type:"Parent")
	redirect_to root_url unless !@user.nil?
	#@parent.user << @user
			redirect_to login_url unless !current_user.nil? and current_user.authenticated? and (@parent.id == current_user.id or current_user.admin?) 

  end

  # POST /parents
  # POST /parents.json
  def create
    @parent = Parent.new(parent_params)
    @parent.students.build
    @parent.students.each do |s|
		if s.nil?
			s.delete
		elsif s.first_name.blank? or s.first_name.nil?
			s.delete
		end		
	end
	respond_to do |format|
      if @parent.save and @parent.user.authenicated
		session[:user_id] = @parent.user.id
        format.html { redirect_to @parent, notice: 'Parent was successfully created.' }
        format.json { render :show, status: :created, location: @parent }
      elsif(@parent.save and !@parent.user.authenicated)
       
			
	format.html { redirect_to root_url, notice: 'Parent was successfully created.Wait for authentication' }

	   else
        format.html { render :new }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parents/1
  # PATCH/PUT /parents/1.json
  def update
	path = request.original_url.split('/')[-1]
	@parent =Parent.find_by(id: path.to_i)
	if !current_user.nil? and current_user.authenticated? and (@parent.id == current_user.id or current_user.admin?) 
   respond_to do |format|
      if @parent.update(parent_params) 
        format.html { redirect_to @parent, notice: 'Parent was successfully updated.' }
        format.json { render :show, status: :ok, location: @parent }
      else
        format.html { render :edit }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
	else
		redirect_to root_url
	end
  end

  # DELETE /parents/1
  # DELETE /parents/1.json
  def destroy
	path = request.original_url.split('/')[-1]
	@parent =Parent.find_by(id: path.to_i)
	@students = @parent.students

	
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to parents_url, notice: 'Parent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_parent
    @parent
    if logged_in? and  current_user.nil? and current_user.userable_type == "Parent"
      @parent = Parent.find_by(id: current_user.userable_id)   
       
    else
      #redirect_to login_url
    end
    
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parent_params
	
      params.require(:parent).permit(:phone_num,user_attributes:[:first_name,:last_name,:email,:password,:password_confirmation],students_attributes:[:id,:first_name,:last_name,:year,:_destroy])

	end
	

end

Online-Booking-System/app/helpers/parents_helper.rb
module ParentsHelper
end

Online-Booking-System/app/views/parents/_form.html.erb
<%= nested_form_for(@parent) do |f| %>
  <% if @parent.errors.any? %>
	
    <div id="error_explanation">
      <h2><%= pluralize(@parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
      <% @parent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.fields_for :user do |u|  %>

  <div class="field">
    <p><%= u.label :first_name %><br></p>
    <p><%= u.text_field :first_name, class: 'input-box' %></p>
  </div>

  <div class="field">
    <p><%= u.label :last_name %><br></p>
    <p><%= u.text_field :last_name, class: 'input-box' %></p>
  </div>


  <div class="field">
    <p><%= u.label :password %><br></p>
    <p><%= u.password_field :password, class: 'input-box' %></p>
  </div>

  <div class="field">
    <p><%= u.label :password_confirmation %><br></p>
    <p><%= u.password_field :password_confirmation, class: 'input-box' %></p>
  </div>

  <div class="field">
    <p><%= u.label :email %><br></p>
    <p><%= u.text_field :email, class: 'input-box' %></p>
  </div>

<% end  %>
 <div class="field">
    <p><%= f.label :phone_num, "Phone Number" %><br></p>
    <p><%= f.text_field :phone_num, class: 'input-box' %></p>
  </div>


	<div id="tasks">
  <%= f.fields_for :students, @parent.students do |task_form| %>
  <div class="field">
    <p style="font-weight:bold">Child<p>
      <p><%= task_form.label :first_name %><br></p>
      <p><%= task_form.text_field :first_name, class: 'input-box' %></p>
      <p><%= task_form.label :last_name %><br></p>
      <p><%= task_form.text_field :last_name, class: 'input-box' %></p>
      
      <p><%= task_form.label :year %><br></p>
      <p><%= task_form.collection_select(:year, StudentClass.all, :id, :StudentClass, {}, {:class => 'input-box'}) %></p>
 
	<p><%= task_form.link_to_remove "Remove this student" %></p>
 
    </div>
  <% end %>
</div>

<p1><%= f.link_to_add "Add another student", :students, :data => { :target => "#tasks" } %></p1>
	  


<div class="actions">
    <p><%= f.submit "Submit", class:'button'%></p>
  </div>
<% end %>

Online-Booking-System/app/views/parents/_newstudent.html.erb
<div class="field">
	<%= f.label :first_name%>
	<%= f.text_field :first_name%>
</div>
<div class="field">
	<%= f.label :last_name%>
	<%= f.text_field :last_name%>
</div>
<div class="field">
	<%= f.label :age%>
	<%= f.number_field :age%>
</div>
<div class="field">
	<%= f.label :year%>
	<%= f.collection_select(:year, StudentClass.all, :id, :StudentClass) %>
</div>

Online-Booking-System/app/views/parents/edit.html.erb
<h1>Editing Parent</h1>

<%= render 'form' %>

<p><%= link_to 'Show', @parent %> |
<%= link_to 'Back', parents_path %></p>

Online-Booking-System/app/views/parents/index.html.erb
<h1>Listing Parents</h1>

<table class="table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email Address</th>
      <th>Phone Number</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <p><% @parents.each do |parent| %>
      <tr>
        <td><%= parent.user.first_name %></td>
        <td><%= parent.user.last_name %></td>
        <td><%= parent.user.email %></td>
        <td><%= parent.phone_num %></td>
        <td><%= link_to 'Edit', edit_parent_path(parent) %></td>
        <td><%= link_to 'Delete', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %></p>
  </tbody>
</table>

<br>

Online-Booking-System/app/views/parents/new.html.erb
<h1>New Parent</h1>

<%= render 'form' %>

<p><%= link_to 'Back', parents_path %></p>

Online-Booking-System/app/views/parents/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Phone Number:</strong>
  <%= @parent.phone_num %>
</p>

<p><%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %></p>