Online-Booking-System/config/routes.rb
Rails.application.routes.draw do
  
  
  resources :activities do
 resources :applications
  end
  resources :parents do
	resources :parents
end 
		resources :users
  resources :teachers

  
resources :students
  
  root 'welcome#index'
  get '/approve' => 'welcome#approve'
  get 'admins/add'=> 'welcome#new'
  post '/approve' => 'welcome#authen'	  
  post 'admins/add' => 'welcome#add_admin'
  get '/register' => 'parents#new'
  get '/registerteacher' => 'teachers#new'
  get '/students/:id/activities' => 'students#activity'

  get '/parents/homepage' => 'sessions#homepage'
  
  delete '/logout' => 'sessions#destroy'	
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/newclass' => 'subjects#new'
  post '/newclass' => 'subjects#create'

   

end

Online-Booking-System/app/models/activity.rb
class Activity < ActiveRecord::Base
	has_one :teacher
	has_many :activity_dates, dependent: :destroy
	has_many :applications, dependent: :destroy
end

Online-Booking-System/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	include SessionsHelper	
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
	@current_user = current_user
    @activities = Activity.all
  end

  # GET /activities/1	
  # GET /activities/1.json
  def show
	redirect_to login_url unless !current_user.nil? and current_user.authenticated?
  end

  # GET /activities/new
  	def new
		redirect_to login_url if current_user.nil? or !current_user.authenticated? or !current_user.admin?
		
		@activity = Activity.new if !current_user.nil? and current_user.authenticated? and current_user.admin?
		flash[:message] = "Invalid privileges for this action"	
 	end

  # GET /activities/1/edit
  def edit
	redirect_to root_url unless !current_user.nil? and current_user.admin? and current_user.authenticated?
  end

  # POST /activities
  # POST /activities.json
  def create
	uploaded_io = params[:activity][:picture]
	params[:activity][:image_link] = uploaded_io.original_filename
	File.open(Rails.root.join('app/assets','images',uploaded_io.original_filename),'wb') do |file|
	file.write(uploaded_io.read)
	end	
    @activity = Activity.new(activity_params)
    @teachers = User.where(["userable_type = ?", "Teacher"])   

    respond_to do |format|
      if @activity.save
      	activity_date = ActivityDate.new(activity_id: @activity.id,date: @activity.StartDate)
      	activity_date.save
      	activity_date = ActivityDate.new(activity_id: @activity.id,date: activity_date.date + 7)
      	while activity_date.date <= @activity.EndDate do
      		activity_date.save	
      		activity_date = ActivityDate.new(activity_id: @activity.id,date: activity_date.date + 7)
      	end
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
        
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        activityDates = ActivityDate.where(activity_id: @activity.id).all
        activityDates.destroy_all
        
        activity_date = ActivityDate.new(activity_id: @activity.id,date: @activity.StartDate)
      	activity_date.save
      	activity_date = ActivityDate.new(activity_id: @activity.id,date: activity_date.date + 7)
      	while activity_date.date <= @activity.EndDate do
      		activity_date.save	
      		activity_date = ActivityDate.new(activity_id: @activity.id,date: activity_date.date + 7)
      	end
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:ActivityName,:ResponsibleTeacher, :Description, :StartClassSuitability, :EndClassSuitability, :StartDate, :EndDate, :StartTime, :EndTime, :NoOfChildren,:image_link)
    end
    

    
    
end

Online-Booking-System/app/helpers/activities_helper.rb
module ActivitiesHelper
end

Online-Booking-System/app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :ActivityName, "Activity Name"%><br>
    <%= f.text_area :ActivityName, class: 'input-box' %>
  </div>

  <div class="field">
    <%= f.label :ResponsibleTeacher, "Responsible Teacher" %><br>
    <%= f.collection_select(:ResponsibleTeacher, User.where("userable_type = 'Teacher'").all, :userable_id, :first_last_name, {}, {:class => 'input-box'}) %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :Description, class: 'input-box' %>
  </div>
  <div class="field">
    <%= f.label :StartClassSuitability, "Age Group Start" %><br>
    <%= f.collection_select(:StartClassSuitability, StudentClass.all, :id, :StudentClass, {}, {:class => 'input-box'}) %>
  </div>
  <div class="field">
    <%= f.label :EndClassSuitability, "Age Group End" %><br>
    <%= f.collection_select(:EndClassSuitability, StudentClass.all, :id, :StudentClass, {}, {:class => 'input-box'}) %>
  </div>
  <div class="field">
    <%= f.label :StartDate, "Start Date" %><br>
    <span class="dropdown-box"><%= f.date_select :StartDate %></span>
  </div>
  <div class="field">
    <%= f.label :EndDate, "End Date" %><br>
    <span class="dropdown-box"><%= f.date_select :EndDate %></span>
  </div>
  <div class="field">
    <%= f.label :StartTime, "Start Time" %><br>
    <span class="dropdown-box1"><%= f.time_select :StartTime%></span>
  </div>
  <div class="field">
    <%= f.label :EndTime, "End Time" %><br>
    <span class="dropdown-box1"><%= f.time_select :EndTime %></span>
  </div>
  <div class="field">
    <%= f.label :NoOfChildren, "Capacity" %><br>
    <%= f.number_field :NoOfChildren, class: 'input-box' %>
  </div>
	<div class="field">
	<%= f.label :picture%>
	<%=f.file_field :picture, class:'browse' %>
	</div>

  <div>
    <%= f.submit "Create Activity", class:'button' %>
  </div>
<% end %>

Online-Booking-System/app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<div class="button">
<p><%= link_to 'Delete', @activity, method: :delete, data: { confirm: 'Are you sure?' } %></p>
</div>

Online-Booking-System/app/views/activities/index.html.erb
<% if !@current_user.nil? and @current_user.admin? and @current_user.authenticated?  %>
<div class="button">
<div id="button1">
<p><%= link_to 'New Activity', new_activity_path %></p>
</div>
<% end  %>
</div>

<div class="table1">
<table class="table">
  <tbody>
    <% @activities.each do |activity| %>
      <tr>
      <th> <%= activity.ActivityName %> </th>
          <td class="image-1"> <%= link_to image_tag(activity.image_link.to_s), activity %> </td>
	</div> 
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

Online-Booking-System/app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

Online-Booking-System/app/views/activities/show.html.erb
<div class="container">
<p>
  <div class="image-2">
  <%= image_tag(@activity.image_link.to_s) %>
  </div>
</p>


<p class="text">
  <strong>Activity:</strong>
  <%= @activity.ActivityName %>
</p>
</div>

<p class="text">

  <strong>Teacher:</strong>
  <%= @activity.ResponsibleTeacher %>
</p>

<p class="text">
  <strong>Description:</strong>
  <%= @activity.Description %>
</p>

<p class="text">
  <strong>Age Group:</strong>
  <%= StudentClass.find(@activity.StartClassSuitability).StudentClass %>
</p>

<p class="text">
  <normal>to:</normal>
  <%= StudentClass.find(@activity.EndClassSuitability).StudentClass %>
</p>

<p class="text">
  <strong>Start Date:</strong>
  <%= @activity.StartDate.strftime("%d-%m-%y") %>
</p>

<p class="text">
  <strong>End Date:</strong>
  <%= @activity.EndDate.strftime("%d-%m-%y") %>
</p>

<p class="text">
  <strong>Start Time:</strong>
  <%= @activity.StartTime.strftime("%H:%M") %>
</p>

<p class="text">
  <strong>End Time:</strong>
  <%= @activity.EndTime.strftime("%H:%M") %>
</p>

<p class="text">
  <strong>Capacity:</strong>
  <%= @activity.NoOfChildren %>

</p>

</div>


<div class="button">
	<div id="button1">
	<%if logged_in? and  current_user.admin == true  %>
	<%= link_to 'Applications for Activity', activity_applications_path(@activity) %>
	<% else %>
	<%= link_to 'Apply for Activity', activity_applications_path(@activity) %>
	<% end %>
	</div>
</div>
<%if logged_in? and  current_user.admin == true  %>
<div class="button">
	<div id="button1">
	
	<%= link_to 'Edit', edit_activity_path(@activity) %>
	
	</div>
</div>
<% end %>
<div class="button">
	<div id="button1">
	<%= link_to 'Back', activities_path %>
	</div>
</div>